version: '3'
services:
  bet365:
    build:
      context: .
      dockerfile: Dockerfile
      no_cache: true
    environment:
      DISCORD_BOT_API_TOKEN: ${DISCORD_BOT_API_TOKEN}
      DISCORD_CHANNEL_ID: ${DISCORD_CHANNEL_ID}
      URL: ${URL}
    restart: always