version: '3'
services:
  bet365-notificator:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    image: bet365-notificator
    container_name: bet-365-notificator
    enviroment:
      DISCORD_BOT_API_TOKEN: ${DISCORD_BOT_API_TOKEN}
      DISCORD_CHANNEL_ID: ${DISCORD_CHANNEL_ID}
      URL: ${URL}